import os

from db import save_analysis
from pipeline import run_subject_pipeline
from report import generate_report


def run_job(job_id: str, job: dict, edf_path: str, subject_id: str) -> None:
    try:
        for progress, message in run_subject_pipeline(edf_path, subject_id):
            if progress == 100 and isinstance(message, dict):
                _finalize_job(job_id, job, message)
            else:
                append_log(job, progress, message)
    except Exception as exc:
        job["status"] = "error"
        job["error"] = str(exc)
        append_log(job, job["progress"], f"ERROR: {exc}")
        save_analysis(
            job_id=job_id,
            subject_id=subject_id,
            status="error",
            error=str(exc),
        )
    finally:
        cleanup_upload(edf_path)


def append_log(job: dict, progress: int, message: str) -> None:
    job["progress"] = progress
    job["logs"].append({"progress": progress, "message": message})


def _finalize_job(job_id: str, job: dict, result: dict) -> None:
    job["result"] = result
    append_log(job, 95, "Generating clinical report with Gemini…")

    try:
        job["report"] = generate_report(result)
        append_log(job, 100, "Report generated successfully")
    except Exception as exc:
        job["report"] = {
            "patient_recording_information": "Report generation failed.",
            "model_prediction_summary": "Structured model outputs are still available in the analysis results.",
            "concept_based_explanation": "",
            "clinical_interpretation": "",
            "confidence_reliability_assessment": f"Technical detail: {exc}",
            "safety_disclaimer": "This report is generated by an AI-based decision support system and is not a standalone diagnostic tool. Clinical correlation with patient history and professional evaluation is required.",
        }
        append_log(job, 100, f"Report error: {exc}")

    job["status"] = "done"
    save_analysis(
        job_id=job_id,
        subject_id=result["subject_id"],
        status="done",
        result=result,
        report=job["report"],
    )


def cleanup_upload(edf_path: str) -> None:
    try:
        os.remove(edf_path)
        os.rmdir(os.path.dirname(edf_path))
    except Exception:
        pass
