import json
import re
import time
from enum import Enum
from statistics import pstdev

import requests

from config import GEMINI_API_KEY, GEMINI_MODEL_URL


# ---------------------------------------------------------------------------
# Constants & enums
# ---------------------------------------------------------------------------

class ClinicalFlag(str, Enum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    SUPPRESSOR = "SUPPRESSOR"


# Pipeline may emit these extended flag names  normalise to canonical three-way taxonomy
_FLAG_NORMALISATION: dict[str, ClinicalFlag] = {
    "STRONG": ClinicalFlag.STRONG,
    "STRONG_DRIVER": ClinicalFlag.STRONG,
    "MODERATE_DRIVER": ClinicalFlag.MODERATE,
    "MODERATE": ClinicalFlag.MODERATE,
    "NEUTRAL": ClinicalFlag.WEAK,
    "WEAK": ClinicalFlag.WEAK,
    "SUPPRESSOR": ClinicalFlag.SUPPRESSOR,
}


def _normalise_flag(raw: str) -> ClinicalFlag:
    return _FLAG_NORMALISATION.get(str(raw).upper(), ClinicalFlag.WEAK)


REPORT_SECTIONS = [
    ("patient_recording_information", "Patient & Recording Information"),
    ("model_prediction_summary", "Clinical Summary"),
    ("concept_based_explanation", "Biomarker Interpretation"),
    ("clinical_interpretation", "Clinical Interpretation"),
    ("confidence_reliability_assessment", "Confidence & Reliability Assessment"),
    ("safety_disclaimer", "Safety Disclaimer"),
]

SAFETY_DISCLAIMER = (
    "This report is generated by an AI-based decision support system and is not a standalone "
    "diagnostic tool. Clinical correlation with patient history and professional evaluation is required."
)

# ---------------------------------------------------------------------------
# Clinical style rules injected into every prompt
# ---------------------------------------------------------------------------

CLINICAL_STYLE_GUIDE = """
Clinical writing conventions:
- Use passive-declarative voice as standard in neurophysiology reports: "activity was observed",
  "findings are consistent with", "the pattern is suggestive of".
- One finding per sentence. Do not chain multiple findings with conjunctions.
- Avoid over-hedging ("may possibly suggest")  use calibrated clinical language
  ("findings are consistent with", "the pattern is indicative of").
- Do not use first or second person. Do not refer to the AI system.
- Refer to the subject as "the subject" or "this recording"  not "the patient"
  (EEG-only context, no clinical contact).
- Numbers: probabilities to two decimal places; durations in whole seconds;
  percentages with one decimal place.
- Spell out all abbreviations on first use within each section.

Evidence-calibration conventions (mandatory):
- FAA findings must acknowledge the heterogeneous and small meta-analytic effect size
  (van der Vinne et al. 2017; Dewaele et al. 2025). Do not present FAA as a reliable
  standalone MDD diagnostic marker; frame it as a prognostic and lateralisation indicator.
- TBR findings must note that theta/beta ratio is primarily an arousal construct derived
  from the ADHD literature and has not been established as a specific MDD biomarker.
- Coherence direction: elevated alpha coherence is the MDD-associated pattern per
  Leuchter et al. 2012 (loss of functional connectivity selectivity). A SUPPRESSOR
  Coherence flag (low coherence, pushing away from MDD prediction) represents preserved
  functional connectivity selectivity  a healthy normative finding. Frame it accordingly.
- Do not use "hyperarousal" as the primary mechanistic explanation for reduced posterior
  alpha. Use "impaired cortical inhibitory efficiency" or "disrupted fronto-parieto-occipital
  connectivity" instead.
- Elevated frontal-central beta is most consistently observed in MDD comorbid with anxiety.
  Contextualise beta findings accordingly.
"""

# ---------------------------------------------------------------------------
# Per-section prompt instructions
# ---------------------------------------------------------------------------

PATIENT_INFO_INSTRUCTION = """
For the Patient & Recording Information section:
- State subject ID, recording duration in seconds, and data source filename.
- One sentence only. Do not interpret or comment.
"""

CLINICAL_SUMMARY_INSTRUCTION = """
For the Clinical Summary section:
1. Open with the clinical impression: classification label, confidence percentage, and
   confidence band (High/Moderate/Low). Do not reference whether the biomarker profile
   supports or qualifies the classification  that framing belongs to interpretation, not summary.
2. Describe temporal stability in plain language.
   - If std < 0.10, use exactly this phrasing: "The classification remained stable across
     the full recording duration." Do not add adverbial qualifiers such as "highly", "very",
     or "remarkably".
   - If std >= 0.12, state the observed range in plain language.
   - Do NOT list mean/std/min/max as a series of raw numbers  summarise in words.
3. Close with one sentence on what the confidence level implies for clinical reliance.
Do not exceed four sentences total. Do not introduce biomarker findings here.
"""

BIOMARKER_INSTRUCTION = """
For the Biomarker Interpretation section:
- Treat each biomarker as an independent neurophysiological measure. Report what this
  subject's brain is doing on each measure purely in terms of neurophysiological
  observation  what was seen, and what it means for brain function.
- Each biomarker has a clinical_flag in the input JSON. Use it as follows:
  - STRONG: The biomarker showed an abnormal pattern  describe the deviation from
    normative expectation and its neurophysiological significance.
  - MODERATE: The biomarker showed a present but not dominant deviation  describe
    the abnormality in calibrated language and state that the effect is secondary
    or moderate rather than the primary biomarker signal.
  - SUPPRESSOR: The biomarker showed a healthy, normative pattern  describe the normal
    finding and confirm what preserved function it reflects. Do not describe this as
    "suppressed" or "reduced". Frame it as a positive neurophysiological observation.
  - WEAK: The biomarker was within expected limits with no meaningful deviation 
    confirm normative status and state what intact function it reflects. If the TCAV
    effect is very small or near-neutral, explicitly note that the biomarker did not
    show a stable directional contribution in this recording.
- For each biomarker, answer three questions in clinical prose:
  1. What is the established normative expectation for this measure in a healthy adult EEG?
  2. What was observed in this subject's recording?
  3. What does this indicate about this subject's neurophysiological state?
- Lead with the most clinically notable finding: STRONG biomarkers first (ordered by degree
  of abnormality), then SUPPRESSOR, then WEAK.
- Do NOT frame any finding relative to the classification. Never write "consistent with the
  predicted class", "supports the classification", "qualifies the prediction", "despite the
  classification", or any similar phrase.
- Do NOT group WEAK or SUPPRESSOR biomarkers into dismissive sentences. Each must be a
  standalone paragraph.
- Vary sentence structure across findings  do not apply the same template to each concept.
- Do not repeat the concept description verbatim. Synthesise into a clinical finding.
- Do not mention raw metric names (TCAV, mean_dd, directional derivative, CAV accuracy).
- FORMATTING: Write each biomarker as a single continuous prose paragraph. Separate each
  paragraph with a single blank line. No sub-headings or numbered sub-items within this section.

CONCEPT-SPECIFIC CLINICAL ACCURACY RULES  these override any templated framing:

FAA (Frontal Alpha Asymmetry, F4 vs F3, 8-12 Hz):
  - The proposed neural mechanism is hemispheric motivational lateralisation via
    approach-withdrawal motivational balance. A positive FAA index (greater right-hemisphere
    alpha, reflecting relative left-hemisphere hyperactivation) has been theoretically
    linked to withdrawal-dominant motivation in MDD.
  - CRITICAL: Meta-analytic evidence (van der Vinne et al. 2017; Dewaele et al. 2025)
    shows FAA has only a small-to-negligible effect size for distinguishing MDD from
    healthy controls, with substantial inter-study heterogeneity. FAA must NOT be
    presented as a reliable standalone diagnostic indicator.
  - STRONG FAA: Describe the hemispheric alpha imbalance observed. State clearly that
    FAA has limited standalone diagnostic specificity and is better regarded as a
    prognostic or treatment-response indicator. Do not frame it as confirming MDD.
  - SUPPRESSOR or WEAK FAA: Confirm that frontal alpha balance was within expected
    limits; no significant hemispheric motivational lateralisation imbalance was identified.

Theta (Frontal Theta Power, Fz/F3/F4, 4-8 Hz):
  - Normative expectation: low frontal theta at rest, reflecting alert and regulated
    prefrontal activity with effective cognitive inhibition.
  - STRONG Theta (elevated): Elevated frontal theta reflects impaired prefrontal
    regulatory tone, sustained internally directed processing, and ruminative cognitive
    engagement (Olbrich & Arns 2013). Note that prefrontal theta cordance is an
    established treatment-response biomarker  elevated baseline theta may have
    prognostic relevance for antidepressant selection.
  - SUPPRESSOR or WEAK Theta: Frontal theta within expected limits indicates preserved
    prefrontal regulatory tone and intact cognitive inhibitory function.

Alpha_Power (Parieto-occipital Alpha, P3/P4/O1/O2, 8-12 Hz):
  - Normative expectation: robust posterior alpha during eyes-closed relaxed wakefulness,
    reflecting intact cortical inhibitory tone and sensory gating.
  - STRONG Alpha_Power (reduced): Reduced posterior alpha in MDD reflects impaired
    cortical inhibitory efficiency and disrupted fronto-parieto-occipital connectivity,
    with documented correlates in attention, verbal learning, working memory, and
    information processing speed. Do NOT use "hyperarousal" as the primary mechanism 
    use "impaired cortical inhibitory efficiency" or "disrupted fronto-parieto-occipital
    connectivity".
  - SUPPRESSOR or WEAK Alpha_Power: Posterior alpha within expected limits indicates
    intact cortical inhibitory tone and preserved sensory gating.

Beta_Power (Frontal-central Beta, F3/F4/C3/C4, 13-30 Hz):
  - Normative expectation: moderate frontal-central beta reflecting active cortical
    engagement and motor readiness.
  - STRONG Beta_Power (elevated): Elevated frontal-central beta reflects cortical
    hyperactivation and is most consistently observed in MDD comorbid with anxiety
    symptoms. It has been linked to prefrontal dysregulation sustaining negative cognitive
    bias and ruminative processing. Note this marker is not depression-specific  it
    should be contextualised with the subject's anxiety symptom history.
  - SUPPRESSOR or WEAK Beta_Power: Beta power within expected limits indicates no
    significant cortical hyperactivation or frontal dysregulation in this recording.

TBR (Theta/Beta Ratio, Fz/F3/F4):
  - ALWAYS include a caveat: TBR is a general cortical arousal efficiency index derived
    primarily from the ADHD literature. It has not been established as a specific MDD
    biomarker. Recent evidence indicates TBR lacks diagnostic reliability even for ADHD
    (Arns et al. 2026 multiverse analysis). Frame it as a non-specific arousal finding.
  - STRONG TBR (elevated): Elevated theta/beta ratio reflects relative predominance of
    slower-frequency activity over faster-frequency activity in the prefrontal region,
    indicating reduced frontal arousal efficiency. State explicitly this is a
    non-MDD-specific marker and requires contextualisation alongside other measures.
  - SUPPRESSOR or WEAK TBR: TBR within expected limits indicates no significant frontal
    arousal imbalance in this recording.

Coherence (Interhemispheric Alpha Coherence, F3-F4, P3-P4, T3-T4, 8-12 Hz):
  - CRITICAL DIRECTION: Leuchter et al. 2012 (PLOS ONE  the primary cited reference)
    found that unmedicated MDD subjects had SIGNIFICANTLY HIGHER overall coherence
    (including alpha band) versus healthy controls  described as a "loss of selectivity"
    in resting functional connectivity. ELEVATED coherence is the MDD-associated pattern.
    Normative (moderate) coherence reflects healthy functional connectivity selectivity.
  - STRONG Coherence (elevated, TCAV > 0.5, driving MDD): Coherence was elevated beyond
    the normative range. Frame as loss of functional connectivity selectivity, consistent
    with the Leuchter 2012 MDD pattern. May reflect over-synchronisation of cortical
    networks at rest with reduced specificity of inter-regional communication.
  - SUPPRESSOR Coherence (low coherence, TCAV < 0.5, pushing AWAY from MDD prediction):
    Coherence was within the normative range, indicating preserved selectivity of
    interhemispheric functional connectivity. This is a neurophysiologically healthy
    finding. Do NOT describe this as "reduced coherence indicating impaired transcallosal
    communication"  that framing is clinically incorrect for this model.
  - WEAK Coherence: Coherence within expected limits; interhemispheric functional
    connectivity selectivity is preserved.
"""

INTERPRETATION_INSTRUCTION = """
For the Clinical Interpretation section:
- Do not re-describe individual biomarkers  those were covered in Biomarker Interpretation.
- Synthesise the overall neurophysiological profile: what do the findings collectively
  suggest about this subject's current brain state, functional regulation, and mental
  health profile?
- Characterise the profile domain: is this predominantly a spectral power dysregulation,
  a connectivity disturbance, a ratio imbalance, or a mixed/diffuse presentation?
- Note any internally inconsistent findings and what such dissociation may indicate about
  the nature or stage of the presentation.
- Evidence weighting: where biomarkers have heterogeneous or limited evidence bases (FAA,
  TBR), note that these carry less interpretive weight than more robustly supported markers
  (Theta, Alpha_Power, Beta_Power, Coherence per Leuchter 2012). Do not treat all six
  concepts as equally established.
- For Coherence specifically: if it is a SUPPRESSOR finding (low coherence, healthy pattern),
  frame this as preserved functional connectivity selectivity  NOT as a pathological
  reduction in transcallosal communication.
- Do NOT frame findings relative to the AI classification or use concordance language.
  The biomarker profile stands independently as a clinical observation.
- Do not reference clinical syndromes or condition names when characterising what is absent.
  Describe what the profile shows, not what it lacks.
- Final paragraph: state that EEG findings reflect neurophysiological state at the time of
  recording, require integration with clinical history and symptom presentation, and do not
  constitute a standalone diagnosis.
"""

RELIABILITY_INSTRUCTION = """
For the Confidence & Reliability Assessment section, write three short paragraphs:
1. Model confidence: confidence score, confidence band, and whether temporal consistency
   supports or undermines confidence.
2. Concept reliability: summarise biomarker detectability without citing raw metric values.
   Use clinical language ("biomarker separation was well-established", "concept boundaries
   showed moderate reliability"). Accurately reflect differential evidence quality:
   - Theta, Alpha_Power, Beta_Power, and Coherence (per Leuchter 2012) have stronger
     neurophysiological evidence bases.
   - FAA carries lower interpretive weight given its heterogeneous meta-analytic evidence
     (van der Vinne et al. 2017).
   - TBR carries lower interpretive weight as an arousal construct not specific to MDD.
   - Do not overstate detectability for within-normal biomarkers.
3. Clinical reliability: overall statement on whether this report should serve as primary
   decision-support or supplementary information:
   - High (>= 90% confidence, high temporal consistency, strong concept reliability on
     robust biomarkers): "findings are suitable as a primary decision-support signal,
     subject to clinical correlation."
   - Moderate: "findings are suitable as supplementary information; clinical interview and
     symptom assessment are recommended before clinical action."
   - Low: "findings are indicative only; clinical assessment should take precedence over
     this report."
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_sections(raw_text: str) -> dict:
    headings = [(title, key) for key, title in REPORT_SECTIONS]
    sections = {key: "" for key, _ in REPORT_SECTIONS}
    current = None

    for line in raw_text.split("\n"):
        stripped = line.strip()
        normalized = stripped.lstrip("#").strip()
        matched = None
        for heading, key in headings:
            pattern = rf"^(?:\d+[\).\s-]+)?{re.escape(heading)}\s*:?\s*(.*)$"
            match = re.match(pattern, normalized, flags=re.IGNORECASE)
            if match:
                matched = key
                trailing = match.group(1).strip()
                if trailing:
                    sections[key] += trailing + "\n"
                break
        if matched:
            current = matched
        elif current:
            sections[current] += line + "\n"

    for key in sections:
        sections[key] = re.sub(r"^Subject ID\s*\n", "Subject ID: ", sections[key])
        sections[key] = sections[key].strip()
    return sections


def _clean_report_text(text: str) -> str:
    """Remove any leaked metric names the model failed to suppress."""
    cleaned = re.sub(
        r"\s*\([^)]*(?:TCAV|mean_dd|directional derivative)[^)]*\)", "",
        text, flags=re.IGNORECASE)
    cleaned = re.sub(r"[^.!\n]*\bTCAV\b[^.!\n]*[.!\n]?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"[^.!\n]*\bmean_dd\b[^.!\n]*[.!\n]?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(
        r"[^.!\n]*\bdirectional derivative\b[^.!\n]*[.!\n]?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()


def _confidence_band(confidence_pct: float) -> str:
    if confidence_pct > 90:
        return "High confidence"
    if confidence_pct >= 70:
        return "Moderate confidence"
    return "Low confidence"


def _temporal_consistency(probabilities: list[float]) -> str:
    if not probabilities:
        return "marked variability across recording segments"
    prob_std = pstdev(probabilities) if len(probabilities) > 1 else 0.0
    if prob_std < 0.05:
        return "highly stable across the recording"
    if prob_std < 0.12:
        return "generally stable with minor fluctuations"
    return "marked variability across recording segments"


def _segment_summary(
    probabilities: list[float],
) -> tuple[float | None, float, float | None, float | None]:
    if not probabilities:
        return None, 0.0, None, None
    mean_val = sum(probabilities) / len(probabilities)
    std_val = pstdev(probabilities) if len(probabilities) > 1 else 0.0
    return mean_val, std_val, min(probabilities), max(probabilities)


def _concept_family(concept_name: str) -> str:
    if concept_name in {"FAA", "Theta", "Alpha_Power", "Beta_Power"}:
        return "spectral power"
    if concept_name == "TBR":
        return "spectral ratios"
    if concept_name == "Coherence":
        return "connectivity"
    return "mixed features"


def _concept_prompt_payload(analysis_result: dict) -> dict:
    concepts = []
    for concept in analysis_result.get("concept_summaries", []):
        tcav = float(concept.get("tcav_score", 0.0))
        mean_dd = float(concept.get("mean_derivative", 0.0))
        flag = _normalise_flag(concept.get("clinical_flag", "WEAK"))
        concepts.append(
            {
                "name": concept.get("concept_name"),
                "tcav_score": tcav,
                "mean_dd": mean_dd,
                "std_dd": float(concept.get("tcav_std", 0.0)),
                "cav_accuracy": float(concept.get("cav_accuracy", 0.0)),
                "clinical_flag": flag,
                "description": concept.get("description", ""),
                "clinical_note": concept.get("clinical_note", ""),
                "mdd_direction": concept.get("mdd_direction", ""),
            }
        )
    return {"concepts": concepts}


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------

def _build_prompt(analysis_result: dict) -> str:
    probabilities = [
        float(v)
        for v in analysis_result.get("raw_explanation", {}).get("segment_mdd_probs", [])
    ]
    mdd_prob = float(analysis_result["prediction"]["probabilities"][1]) / 100.0
    hc_prob = float(analysis_result["prediction"]["probabilities"][0]) / 100.0
    confidence_pct = float(analysis_result["prediction"]["confidence"])
    raw_label = analysis_result["prediction"].get("raw_label", "HC")
    display_label = analysis_result["prediction"].get("label", "Healthy")

    mean_prob, std_prob, min_prob, max_prob = _segment_summary(probabilities)

    subject_data = {
        "subject_id": analysis_result["subject_id"],
        "edf_file": analysis_result.get("raw_explanation", {}).get("edf_path", ""),
        "recording_seconds": analysis_result.get("biomarkers", {}).get("recording_seconds"),
        "prediction": {
            "label": display_label,
            "raw_label": raw_label,
            "confidence_percent": confidence_pct,
            "confidence_band": _confidence_band(confidence_pct),
            "depressed_probability": round(mdd_prob, 2),
            "healthy_probability": round(hc_prob, 2),
            "temporal_consistency": _temporal_consistency(probabilities),
            "mean_probability": round(mean_prob, 3) if mean_prob is not None else None,
            "probability_std": round(std_prob, 3) if std_prob else 0.0,
            "probability_min": round(min_prob, 3) if min_prob is not None else None,
            "probability_max": round(max_prob, 3) if max_prob is not None else None,
        },
        **_concept_prompt_payload(analysis_result),
    }

    section_titles = "\n".join(title for _, title in REPORT_SECTIONS)

    # ------------------------------------------------------------------
    # Few-shot example 1
    # MDD prediction, one STRONG (Theta), one WEAK (FAA), one WEAK (Coherence)
    # Demonstrates: abnormal-first ordering, FAA evidence caveat, Coherence
    # WEAK = normative selectivity (healthy), no concordance framing
    # ------------------------------------------------------------------
    few_shot_input_1 = {
        "subject_id": "EXAMPLE_001",
        "edf_file": "example_recording.edf",
        "recording_seconds": 300,
        "prediction": {
            "label": "Depressed",
            "raw_label": "MDD",
            "confidence_percent": 84.2,
            "confidence_band": "Moderate confidence",
            "depressed_probability": 0.84,
            "healthy_probability": 0.16,
            "temporal_consistency": "generally stable with minor fluctuations",
            "mean_probability": 0.801,
            "probability_std": 0.051,
            "probability_min": 0.724,
            "probability_max": 0.872,
        },
        "concepts": [
            {
                "name": "Theta",
                "tcav_score": 0.82,
                "mean_dd": 0.14,
                "std_dd": 0.04,
                "cav_accuracy": 0.91,
                "clinical_flag": "STRONG",
                "description": "Frontal Theta Power (Fz/F3/F4, 48 Hz)",
                "clinical_note": (
                    "Elevated frontal theta associated with ruminative cognition, "
                    "impaired prefrontal regulatory tone, and reduced top-down "
                    "cognitive inhibition. Frontal theta cordance is an established "
                    "antidepressant treatment-response biomarker."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "FAA",
                "tcav_score": 0.12,
                "mean_dd": -0.08,
                "std_dd": 0.03,
                "cav_accuracy": 0.88,
                "clinical_flag": "WEAK",
                "description": "Frontal Alpha Asymmetry (F4 vs F3, 812 Hz)",
                "clinical_note": (
                    "FAA within expected limits; no significant hemispheric "
                    "motivational lateralisation imbalance identified. FAA has "
                    "a heterogeneous meta-analytic evidence base and limited "
                    "standalone diagnostic value in MDD."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "Coherence",
                "tcav_score": 0.09,
                "mean_dd": -0.04,
                "std_dd": 0.02,
                "cav_accuracy": 0.86,
                "clinical_flag": "WEAK",
                "description": "Interhemispheric Alpha Coherence (F3F4, P3P4, T3T4, 812 Hz)",
                "clinical_note": (
                    "Interhemispheric alpha coherence within the normative range, "
                    "indicating preserved functional connectivity selectivity. "
                    "Elevated coherence is the MDD-associated pattern per Leuchter "
                    "et al. 2012; normative values confirm healthy connectivity organisation."
                ),
                "mdd_direction": "positive",
            },
        ],
    }

    few_shot_output_1 = f"""Patient & Recording Information
Subject ID: EXAMPLE_001. Recording duration: 300 seconds. Data source: example_recording.edf.

Clinical Summary
EEG analysis yielded a classification of Depressed with 84.2% confidence (moderate confidence). The classification remained stable across the full recording duration. At this confidence level, findings are appropriate as supplementary decision-support information pending clinical correlation.

Biomarker Interpretation
Frontal theta power (48 Hz; electrodes Fz, F3, F4): In a neurologically healthy adult, frontal theta power is typically low at rest, reflecting a state of alert, regulated cortical activity with effective prefrontal inhibitory tone. In this subject, frontal theta power was markedly elevated, indicating sustained prefrontal engagement associated with ruminative ideation, impaired cognitive inhibition, and reduced top-down regulatory efficiency. This finding is clinically notable: prefrontal theta cordance is an established predictor of antidepressant treatment response, and elevated baseline theta may have prognostic relevance for treatment selection.

Frontal alpha asymmetry (FAA; 812 Hz; F4 relative to F3): Normatively, frontal alpha power is broadly symmetric between hemispheres, reflecting balanced bilateral engagement of approach and withdrawal motivational systems. In this subject, the alpha asymmetry index was within expected limits, indicating no clinically significant hemispheric imbalance in frontal inhibitory activity. It should be noted that FAA carries limited standalone diagnostic weight in this context: meta-analytic evidence demonstrates only a small effect size for FAA as a discriminator of MDD from healthy controls, with substantial heterogeneity across studies.

Interhemispheric alpha coherence (F3F4, P3P4, T3T4; 812 Hz): Research in unmedicated MDD subjects has identified elevated alpha coherence  reflecting a loss of functional connectivity selectivity  as the characteristic resting-state coherence deviation in depression (Leuchter et al. 2012). In this subject, interhemispheric alpha coherence was within the expected normative range across all assessed electrode pairs, indicating preserved selectivity of bilateral cortical coordination. This finding reflects intact functional connectivity organisation in this recording.

Clinical Interpretation
The neurophysiological profile of this subject is characterised by a focal spectral power abnormality  specifically, marked frontal theta elevation  against a background of preserved functional connectivity and symmetric frontal alpha. This dissociation between spectral power dysregulation and intact interhemispheric coordination is clinically informative: it suggests that the predominant neurophysiological disturbance is localised to prefrontal regulatory circuits rather than reflecting network-wide disruption.

Among the assessed biomarkers, frontal theta carries the strongest neurophysiological evidence base for the observed pattern. FAA, while within normal limits in this recording, warrants lower interpretive weight given its heterogeneous meta-analytic evidence base and should not be used as a diagnostic anchor. The preserved coherence profile confirms that interhemispheric functional connectivity selectivity is intact.

EEG findings reflect the subject's neurophysiological state at the time of recording. These observations require integration with clinical history, current symptom presentation, and professional evaluation, and do not constitute a standalone diagnosis.

Confidence & Reliability Assessment
Prediction confidence was 84.2% (moderate confidence), and classification probability showed minor fluctuation across recording segments, which is consistent with this confidence level.

Frontal theta power showed well-established concept separation in this recording and represents the primary neurophysiological driver of the biomarker profile. Interhemispheric alpha coherence showed adequate detectability, consistent with its normative status. Frontal alpha asymmetry showed weaker concept separation, consistent with its more heterogeneous evidence base; findings from this measure carry reduced interpretive weight.

Findings are suitable as supplementary decision-support information. Clinical interview and symptom assessment are recommended before clinical action is taken on the basis of this report.

Safety Disclaimer
{SAFETY_DISCLAIMER}"""

    # ------------------------------------------------------------------
    # Few-shot example 2
    # MDD prediction, one SUPPRESSOR (Coherence  normative, healthy pattern),
    # two WEAK biomarkers
    # KEY CORRECTION: Coherence SUPPRESSOR = low coherence pushing AWAY from MDD =
    # preserved functional connectivity selectivity = healthy finding.
    # The MDD-associated pattern is ELEVATED coherence (Leuchter 2012).
    # ------------------------------------------------------------------
    few_shot_input_2 = {
        "subject_id": "EXAMPLE_002",
        "edf_file": "example_suppressor.edf",
        "recording_seconds": 295,
        "prediction": {
            "label": "Depressed",
            "raw_label": "MDD",
            "confidence_percent": 97.6,
            "confidence_band": "High confidence",
            "depressed_probability": 0.98,
            "healthy_probability": 0.02,
            "temporal_consistency": "highly stable across the recording",
            "mean_probability": 0.971,
            "probability_std": 0.012,
            "probability_min": 0.951,
            "probability_max": 0.988,
        },
        "concepts": [
            {
                "name": "Coherence",
                "tcav_score": 0.21,
                "mean_dd": -0.13,
                "std_dd": 0.03,
                "cav_accuracy": 0.92,
                "clinical_flag": "SUPPRESSOR",
                "description": "Interhemispheric Alpha Coherence (F3F4, P3P4, T3T4, 812 Hz)",
                "clinical_note": (
                    "Interhemispheric alpha coherence within the normative range, "
                    "indicating preserved functional connectivity selectivity. "
                    "Elevated coherence is the MDD-associated pattern per Leuchter "
                    "et al. 2012; normative values here reflect a healthy connectivity "
                    "profile, actively reducing the model's MDD prediction."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "Theta",
                "tcav_score": 0.18,
                "mean_dd": 0.03,
                "std_dd": 0.02,
                "cav_accuracy": 0.74,
                "clinical_flag": "WEAK",
                "description": "Frontal Theta Power (Fz/F3/F4, 48 Hz)",
                "clinical_note": (
                    "Frontal theta within expected limits; prefrontal regulatory "
                    "tone and cognitive inhibitory function preserved."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "FAA",
                "tcav_score": 0.11,
                "mean_dd": -0.02,
                "std_dd": 0.01,
                "cav_accuracy": 0.71,
                "clinical_flag": "WEAK",
                "description": "Frontal Alpha Asymmetry (F4 vs F3, 812 Hz)",
                "clinical_note": (
                    "Alpha asymmetry within expected limits; no significant hemispheric "
                    "motivational lateralisation imbalance identified. FAA has limited "
                    "standalone diagnostic value in MDD."
                ),
                "mdd_direction": "positive",
            },
        ],
    }

    few_shot_output_2 = f"""Patient & Recording Information
Subject ID: EXAMPLE_002. Recording duration: 295 seconds. Data source: example_suppressor.edf.

Clinical Summary
EEG analysis yielded a classification of Depressed with 97.6% confidence (high confidence). The classification remained stable across the full recording duration. At this confidence level, findings are suitable as a primary decision-support signal, subject to clinical correlation.

Biomarker Interpretation
Interhemispheric alpha coherence (F3F4, P3P4, T3T4; 812 Hz): Research in unmedicated MDD subjects has identified elevated alpha coherence  characterised as a loss of functional connectivity selectivity  as the primary resting-state coherence deviation in depression, with prefrontal regions serving as primary network hubs (Leuchter et al. 2012). In this subject, interhemispheric alpha coherence was within the expected normative range across all assessed electrode pairs, indicating preserved selectivity of bilateral cortical coordination. This reflects intact functional connectivity organisation, without the over-synchronisation pattern associated with MDD in the resting-state neurophysiology literature.

Frontal theta power (48 Hz; electrodes Fz, F3, F4): In a neurologically healthy adult, frontal theta power is typically low at rest, consistent with alert and regulated prefrontal activity. In this subject, frontal theta power was within expected limits, indicating that prefrontal regulatory tone and cognitive inhibitory processes were not markedly disrupted at the time of recording.

Frontal alpha asymmetry (FAA; 812 Hz; F4 relative to F3): Normatively, frontal alpha is broadly symmetric between hemispheres, reflecting balanced bilateral engagement of approach and withdrawal motivational systems. The alpha asymmetry index in this subject was within expected limits, and no clinically significant hemispheric imbalance in frontal inhibitory activity was identified. FAA carries limited standalone diagnostic weight in this context, given its heterogeneous meta-analytic evidence base in MDD.

Clinical Interpretation
The neurophysiological profile of this subject is notable for the absence of detectable spectral power abnormality or functional connectivity disruption across the assessed biomarker domains. Frontal theta, frontal alpha asymmetry, and interhemispheric alpha coherence were each within normative limits, indicating preserved prefrontal regulatory tone, balanced hemispheric motivational engagement, and intact functional connectivity selectivity respectively.

Among the assessed biomarkers, frontal theta and interhemispheric coherence carry the stronger neurophysiological evidence bases. Both are within normal limits in this recording. FAA carries lower interpretive weight given its heterogeneous diagnostic evidence in MDD and should not be used as an anchor finding. The overall neurophysiological profile does not reveal a clear spectral or connectivity abnormality in this recording; the model classification is driven by more subtle signal features not directly captured by any single biomarker domain assessed here.

EEG findings reflect the subject's neurophysiological state at the time of recording. These observations require integration with clinical history, current symptom presentation, and professional evaluation, and do not constitute a standalone diagnosis.

Confidence & Reliability Assessment
Prediction confidence was 97.6% (high confidence), and the classification remained stable across recording segments, which strongly supports the reliability of this output.

Biomarker concept detectability in this recording was moderate overall. Interhemispheric alpha coherence showed well-established concept separation, providing a reliable neurophysiological reference point. Frontal theta and frontal alpha asymmetry showed adequate but less robust separation; FAA in particular carries lower interpretive weight given its limited MDD-specific evidence base.

Findings are suitable as a primary decision-support signal, subject to clinical correlation.

Safety Disclaimer
{SAFETY_DISCLAIMER}"""

    # ------------------------------------------------------------------
    # Few-shot example 3
    # HC prediction, two STRONG (TBR, Coherence elevated  notable but not dominant),
    # four SUPPRESSOR (FAA, Theta, Alpha_Power, Beta_Power  all healthy signals)
    # Demonstrates: healthy profile framing, SUPPRESSOR = intact/healthy signal,
    # STRONG Coherence on HC = elevated coherence is noteworthy (Leuchter 2012 pattern)
    # but model classifies HC overall, TBR noted as non-MDD-specific arousal measure
    # ------------------------------------------------------------------
    few_shot_input_3 = {
        "subject_id": "EXAMPLE_003",
        "edf_file": "example_hc_mixed.edf",
        "recording_seconds": 305,
        "prediction": {
            "label": "Healthy",
            "raw_label": "HC",
            "confidence_percent": 97.7,
            "confidence_band": "High confidence",
            "depressed_probability": 0.02,
            "healthy_probability": 0.98,
            "temporal_consistency": "highly stable across the recording",
            "mean_probability": 0.023,
            "probability_std": 0.008,
            "probability_min": 0.012,
            "probability_max": 0.038,
        },
        "concepts": [
            {
                "name": "TBR",
                "tcav_score": 0.72,
                "mean_dd": 0.0000,
                "std_dd": 0.0000,
                "cav_accuracy": 1.00,
                "clinical_flag": "STRONG",
                "description": "Theta/Beta Ratio (Fz/F3/F4, 48 Hz / 1330 Hz)",
                "clinical_note": (
                    "Elevated theta/beta ratio indicating relative predominance of "
                    "slower-frequency activity in the prefrontal region, reflecting "
                    "reduced frontal arousal efficiency. TBR is a general cortical "
                    "arousal index derived from the ADHD literature and is not "
                    "established as a specific MDD biomarker."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "Coherence",
                "tcav_score": 0.93,
                "mean_dd": 0.0001,
                "std_dd": 0.0000,
                "cav_accuracy": 1.00,
                "clinical_flag": "STRONG",
                "description": "Interhemispheric Alpha Coherence (F3F4, P3P4, T3T4, 812 Hz)",
                "clinical_note": (
                    "Elevated interhemispheric alpha coherence beyond the normative "
                    "midrange, reflecting heightened bilateral cortical synchrony. "
                    "Elevated coherence is associated with a loss of functional "
                    "connectivity selectivity in MDD (Leuchter et al. 2012); its "
                    "clinical significance here requires contextualisation."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "FAA",
                "tcav_score": 0.00,
                "mean_dd": -0.0011,
                "std_dd": 0.0000,
                "cav_accuracy": 1.00,
                "clinical_flag": "SUPPRESSOR",
                "description": "Frontal Alpha Asymmetry (F4 vs F3, 812 Hz)",
                "clinical_note": (
                    "Hemispheric alpha asymmetry within expected limits; bilateral "
                    "motivational balance intact. FAA has limited standalone diagnostic "
                    "value in MDD due to heterogeneous meta-analytic evidence."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "Theta",
                "tcav_score": 0.00,
                "mean_dd": -0.0007,
                "std_dd": 0.0000,
                "cav_accuracy": 1.00,
                "clinical_flag": "SUPPRESSOR",
                "description": "Frontal Theta Power (Fz/F3/F4, 48 Hz)",
                "clinical_note": (
                    "Frontal theta within expected limits; prefrontal regulatory "
                    "tone and cognitive inhibitory function intact."
                ),
                "mdd_direction": "positive",
            },
            {
                "name": "Alpha_Power",
                "tcav_score": 0.00,
                "mean_dd": -0.0009,
                "std_dd": 0.0000,
                "cav_accuracy": 1.00,
                "clinical_flag": "SUPPRESSOR",
                "description": "Parieto-occipital Alpha Power (P3/P4/O1/O2, 812 Hz)",
                "clinical_note": (
                    "Posterior alpha power within expected limits; cortical inhibitory "
                    "efficiency and fronto-parieto-occipital connectivity intact."
                ),
                "mdd_direction": "negative",
            },
            {
                "name": "Beta_Power",
                "tcav_score": 0.00,
                "mean_dd": -0.0016,
                "std_dd": 0.0000,
                "cav_accuracy": 1.00,
                "clinical_flag": "SUPPRESSOR",
                "description": "Frontal-central Beta Power (F3/F4/C3/C4, 1330 Hz)",
                "clinical_note": (
                    "Frontal-central beta power within expected limits; no cortical "
                    "hyperactivation or prefrontal dysregulation identified. Elevated "
                    "beta is most consistently associated with MDD comorbid with anxiety."
                ),
                "mdd_direction": "positive",
            },
        ],
    }

    few_shot_output_3 = f"""Patient & Recording Information
Subject ID: EXAMPLE_003. Recording duration: 305 seconds. Data source: example_hc_mixed.edf.

Clinical Summary
EEG analysis yielded a classification of Healthy with 97.7% confidence (high confidence). The classification remained stable across the full recording duration. At this confidence level, findings are suitable as a primary decision-support signal, subject to clinical correlation.

Biomarker Interpretation
Theta/beta ratio (TBR; 48 Hz relative to 1330 Hz; electrodes Fz, F3, F4): In a neurologically healthy adult, the theta-to-beta ratio at rest is typically low, reflecting efficient frontal arousal regulation and active cognitive engagement. In this subject, the theta/beta ratio was elevated relative to normative expectation, indicating a relative predominance of slower-frequency activity over faster-frequency activity in the prefrontal region and reduced frontal arousal efficiency. It is important to note that TBR is a general cortical arousal index derived primarily from the ADHD literature; its specificity as an MDD biomarker has not been established, and this finding should not be interpreted as MDD-specific without contextualisation against clinical presentation.

Interhemispheric alpha coherence (F3F4, P3P4, T3T4; 812 Hz): Research has identified elevated resting-state alpha coherence  representing a loss of functional connectivity selectivity  as a characteristic pattern in unmedicated MDD, with prefrontal regions as primary network hubs (Leuchter et al. 2012). In this subject, interhemispheric alpha coherence was elevated beyond the typical normative midrange, indicating heightened bilateral cortical synchrony. This degree of over-synchronisation warrants clinical contextualisation; in isolation it does not constitute a diagnostic finding, but it is a deviation from the selective, moderate coherence expected in neurophysiologically healthy adults.

Frontal theta power (48 Hz; electrodes Fz, F3, F4): Healthy adults at rest typically exhibit low frontal theta power, consistent with regulated prefrontal activity and effective cognitive inhibition. In this subject, frontal theta power was within the expected normative range, indicating that prefrontal regulatory tone was intact at the time of recording.

Frontal alpha asymmetry (FAA; 812 Hz; F4 relative to F3): Normatively, frontal alpha is broadly symmetric between hemispheres, reflecting balanced bilateral motivational engagement. Hemispheric alpha asymmetry was within expected limits in this subject; no significant imbalance in frontal inhibitory lateralisation was identified. FAA carries limited interpretive weight in this context given its heterogeneous meta-analytic evidence base as an MDD discriminator.

Parieto-occipital alpha power (812 Hz; P3, P4, O1, O2): Healthy adults typically demonstrate robust posterior alpha during relaxed wakefulness, associated with intact cortical inhibitory efficiency and effective fronto-parieto-occipital connectivity. Posterior alpha power was within the normative range in this subject, indicating preserved cortical inhibitory tone and sensory gating function at the time of recording.

Frontal-central beta power (1330 Hz; F3, F4, C3, C4): Normatively, beta power in frontal and central regions reflects active cortical engagement. In this subject, frontal-central beta power was within expected limits, indicating no cortical hyperactivation or prefrontal dysregulation. Elevated frontal beta is most consistently observed in MDD comorbid with anxiety symptoms; its absence here is consistent with the overall neurophysiological profile.

Clinical Interpretation
The neurophysiological profile of this subject is characterised by two notable findings  an elevated theta/beta ratio and supranormative interhemispheric alpha coherence  against a background of preserved spectral power across frontal theta, posterior alpha, frontal alpha asymmetry, and frontal-central beta domains.

The elevated interhemispheric alpha coherence is the more neurophysiologically substantive finding, given the established evidence base linking elevated alpha coherence with loss of functional connectivity selectivity in MDD (Leuchter et al. 2012). Its presence in a subject classified as Healthy warrants clinical note: it may reflect a subclinical network-level deviation or a variant within the normal distribution, and should be contextualised with clinical history. The elevated TBR reflects a general reduction in frontal arousal efficiency; this is a non-specific finding not specific to any psychiatric diagnosis and carries lower interpretive weight. The broad preservation of spectral power measures across other assessed domains  including theta, posterior alpha, and beta  supports the overall characterisation of this recording as neurophysiologically within healthy limits. FAA was within normal limits and, given its limited meta-analytic evidence base, contributes minimal diagnostic weight here.

EEG findings reflect the subject's neurophysiological state at the time of recording. These observations require integration with clinical history, current symptom presentation, and professional evaluation, and do not constitute a standalone diagnosis.

Confidence & Reliability Assessment
Prediction confidence was 97.7% (high confidence), and the classification remained stable across recording segments, which strongly supports the reliability of this output.

Biomarker detectability was well-established across all assessed concepts in this recording. Interhemispheric alpha coherence and theta/beta ratio showed strong concept separation; however, TBR carries reduced interpretive weight as a general arousal construct not specific to MDD. The four within-normal biomarkers (frontal theta, FAA, posterior alpha, frontal-central beta) demonstrated robust separation consistent with their normative status, though FAA carries lower evidence-based weight among these. The overall biomarker evidence base is considered highly reliable for the dominant findings.

Findings are suitable as a primary decision-support signal, subject to clinical correlation.

Safety Disclaimer
{SAFETY_DISCLAIMER}"""

    return f"""You are a senior clinical neurophysiology reporting specialist. Your task is to convert structured EEG AI analysis output into a formal clinical report suitable for hospital use.

{CLINICAL_STYLE_GUIDE}

Generate a complete report with exactly these section headings (in this order):
{section_titles}

Per-section instructions:

{PATIENT_INFO_INSTRUCTION}
{CLINICAL_SUMMARY_INSTRUCTION}
{BIOMARKER_INSTRUCTION}
{INTERPRETATION_INSTRUCTION}
{RELIABILITY_INSTRUCTION}

Safety Disclaimer: reproduce exactly: "{SAFETY_DISCLAIMER}"

General constraints:
- Use only the information provided in the input JSON. Do not hallucinate clinical facts, significance tests, or reference values.
- Do not include raw JSON, code blocks, or markdown formatting in the output.
- Do not use casual language or hedging phrases such as "may possibly suggest".
- The report must be self-contained and readable without reference to the input data.

FEW-SHOT EXAMPLES

Example 1  MDD prediction, one STRONG biomarker (Theta), two WEAK biomarkers (FAA, Coherence within normal):

Input JSON:
{json.dumps(few_shot_input_1, indent=2)}

Output report:
{few_shot_output_1}

---

Example 2  MDD prediction, one SUPPRESSOR biomarker (Coherence  normative coherence is a healthy finding; elevated coherence is the MDD pattern), two WEAK biomarkers:

Input JSON:
{json.dumps(few_shot_input_2, indent=2)}

Output report:
{few_shot_output_2}

---

Example 3  HC prediction, two STRONG biomarkers (TBR elevated  non-specific arousal; Coherence elevated  notable per Leuchter 2012 but not dominant), four SUPPRESSOR biomarkers (all healthy/intact signals):

Input JSON:
{json.dumps(few_shot_input_3, indent=2)}

Output report:
{few_shot_output_3}

---

INPUT JSON:
{json.dumps(subject_data, indent=2)}

OUTPUT REPORT:"""


# ---------------------------------------------------------------------------
# Local fallback report (used when Gemini is unavailable)
# ---------------------------------------------------------------------------

def _activity_descriptor(clinical_flag: ClinicalFlag, mean_dd: float) -> str:
    """Clinical activity descriptor  uses flag as primary signal, DD only for direction."""
    if clinical_flag in {ClinicalFlag.STRONG, ClinicalFlag.MODERATE}:
        return "elevated" if mean_dd >= 0 else "reduced"
    # Both SUPPRESSOR and WEAK are within normal limits
    return "within expected limits"


def _suppressor_context(raw_label: str) -> str:
    """Framing for SUPPRESSOR biomarker depending on the overall prediction direction."""
    if raw_label == "MDD":
        return "preserved"
    return "intact"


def _weak_effect_note(tcav: float) -> str:
    """Calibrated wording for non-salient or near-neutral TCAV effects."""
    if abs(tcav - 0.5) < 0.05:
        return (
            "The concept effect was near-neutral in this recording and did not show a "
            "stable directional contribution."
        )
    if 0.35 <= tcav <= 0.65:
        return (
            "The concept effect was small in this recording and did not indicate a "
            "reliably expressed directional abnormality."
        )
    return ""


def _coherence_suppressor_note() -> str:
    """
    Returns the clinically correct local-fallback note for a Coherence SUPPRESSOR.
    Coherence SUPPRESSOR = normative coherence = healthy functional connectivity
    selectivity. The MDD-associated pattern is ELEVATED coherence (Leuchter 2012).
    """
    return (
        "Interhemispheric alpha coherence was within the expected normative range, "
        "indicating preserved selectivity of functional connectivity between assessed "
        "electrode pairs. The MDD-associated pattern is elevated coherence reflecting "
        "loss of connectivity selectivity (Leuchter et al. 2012); normative values "
        "here confirm a neurophysiologically healthy connectivity profile."
    )


def _coherence_strong_note() -> str:
    """
    Returns the clinically correct local-fallback note for a Coherence STRONG finding.
    STRONG Coherence = elevated coherence = loss of connectivity selectivity = MDD pattern.
    """
    return (
        "Interhemispheric alpha coherence was elevated beyond the normative range, "
        "indicating heightened bilateral cortical synchrony and loss of functional "
        "connectivity selectivity, consistent with the resting-state pattern identified "
        "in MDD (Leuchter et al. 2012)."
    )


def _build_local_report(analysis_result: dict, technical_note: str | None = None) -> dict:
    explanation = analysis_result.get("raw_explanation", {})
    subject_id = analysis_result.get("subject_id", "Unknown subject")
    edf_file = explanation.get("edf_path", "")
    recording_seconds = analysis_result.get("biomarkers", {}).get("recording_seconds")
    prediction = analysis_result.get("prediction", {})
    label = prediction.get("label", "Unknown")
    raw_label = prediction.get("raw_label", "HC")
    confidence_pct = float(prediction.get("confidence", 0.0))
    probabilities = explanation.get("segment_mdd_probs", [])
    mdd_prob = (
        float(prediction.get("probabilities", [0, 0])[1]) / 100.0
        if prediction.get("probabilities") else 0.0
    )
    hc_prob = (
        float(prediction.get("probabilities", [0, 0])[0]) / 100.0
        if prediction.get("probabilities") else 0.0
    )
    consistency = _temporal_consistency(probabilities)
    mean_prob, std_prob, min_prob, max_prob = _segment_summary(probabilities)
    band = _confidence_band(confidence_pct)

    # Parse concepts
    concepts = []
    for concept in analysis_result.get("concept_summaries", []):
        tcav = float(concept.get("tcav_score", 0.0))
        mean_dd = float(concept.get("mean_derivative", 0.0))
        flag = _normalise_flag(concept.get("clinical_flag", "WEAK"))
        concepts.append(
            {
                "name": concept.get("concept_name", ""),
                "tcav": tcav,
                "mean_dd": mean_dd,
                "std_dd": float(concept.get("tcav_std", 0.0)),
                "cav_accuracy": float(concept.get("cav_accuracy", 0.0)) * 100.0,
                "clinical_flag": flag,
                "description": concept.get("description", ""),
                "clinical_note": concept.get("clinical_note", "").rstrip("."),
            }
        )

    strong = sorted(
        [c for c in concepts if c["clinical_flag"] == ClinicalFlag.STRONG],
        key=lambda c: abs(c["mean_dd"]),
        reverse=True,
    )
    moderate = sorted(
        [c for c in concepts if c["clinical_flag"] == ClinicalFlag.MODERATE],
        key=lambda c: abs(c["mean_dd"]),
        reverse=True,
    )
    suppressors = [c for c in concepts if c["clinical_flag"] == ClinicalFlag.SUPPRESSOR]
    weak = [c for c in concepts if c["clinical_flag"] == ClinicalFlag.WEAK]

    # Dominant domain  prioritise abnormal drivers; on HC, SUPPRESSORs are healthy signals
    active_abnormal = strong + moderate
    domain_sources = active_abnormal if active_abnormal else (
        suppressors if raw_label == "MDD" else []
    )
    family_scores: dict[str, float] = {
        "spectral power": 0.0, "spectral ratios": 0.0, "connectivity": 0.0
    }
    for c in domain_sources:
        fam = _concept_family(c["name"])
        if fam in family_scores:
            family_scores[fam] += abs(c["mean_dd"]) if abs(c["mean_dd"]) > 1e-4 else 1.0
    dominant_family = (
        max(family_scores, key=family_scores.get)
        if any(v > 0 for v in family_scores.values())
        else "mixed features"
    )

    # --- Patient & Recording Information ---
    patient_info = (
        f"Subject ID: {subject_id}. "
        f"Recording duration: {recording_seconds} seconds. "
        f"Data source: {edf_file or 'EDF path not provided'}."
    )

    # --- Clinical Summary ---
    if "stable" in consistency:
        stability_sentence = "The classification remained stable across the full recording duration."
    else:
        range_text = (
            f"from {min_prob:.2f} to {max_prob:.2f}"
            if min_prob is not None and max_prob is not None
            else "across segments"
        )
        stability_sentence = (
            f"Classification confidence varied across recording segments (range {range_text}), "
            f"which introduces uncertainty in the overall assessment."
        )

    reliance_map = {
        "High confidence": (
            "findings are suitable as a primary decision-support signal, "
            "subject to clinical correlation."
        ),
        "Moderate confidence": (
            "findings are appropriate as supplementary decision-support information "
            "pending clinical correlation."
        ),
        "Low confidence": (
            "findings are indicative only; clinical assessment should take "
            "precedence over this report."
        ),
    }
    reliance_sentence = (
        f"At this confidence level, "
        f"{reliance_map.get(band, 'clinical correlation is required.')}"
    ).capitalize()

    model_summary = (
        f"EEG analysis yielded a classification of {label} with {confidence_pct:.1f}% "
        f"confidence ({band.lower()}). "
        f"{stability_sentence} "
        f"{reliance_sentence}"
    )

    # --- Biomarker Interpretation ---
    ordered_concepts = (
        sorted(strong, key=lambda c: abs(c["mean_dd"]), reverse=True)
        + moderate
        + suppressors
        + weak
    )

    biomarker_lines = []
    for c in ordered_concepts:
        desc = c["description"] or c["name"]
        note = c["clinical_note"] if c["clinical_note"] else c["description"]
        name = c["name"]
        flag = c["clinical_flag"]
        mean_dd = c["mean_dd"]
        tcav = c["tcav"]

        if flag == ClinicalFlag.STRONG:
            # Coherence STRONG = elevated coherence = loss of connectivity selectivity = MDD
            if name == "Coherence":
                biomarker_lines.append(f"{desc}: {_coherence_strong_note()}")
            elif name == "TBR":
                # TBR: always include the non-specificity caveat
                activity = _activity_descriptor(flag, mean_dd)
                biomarker_lines.append(
                    f"{desc}: In this recording, the theta/beta ratio was {activity} "
                    f"relative to normative expectation, indicating reduced frontal "
                    f"arousal efficiency. {note}. "
                    f"It should be noted that the theta/beta ratio is a general cortical "
                    f"arousal index derived primarily from the ADHD literature and has "
                    f"not been established as a specific MDD biomarker; this finding "
                    f"requires contextualisation alongside other spectral measures."
                )
            elif name == "FAA":
                # FAA STRONG: include evidence caveat
                activity = _activity_descriptor(flag, mean_dd)
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation. {note}. "
                    f"Frontal alpha asymmetry carries limited standalone diagnostic "
                    f"specificity in this context; meta-analytic evidence demonstrates "
                    f"only a small effect size for FAA as an MDD discriminator, with "
                    f"substantial inter-study heterogeneity."
                )
            elif name == "Beta_Power":
                # Beta STRONG: include anxiety-comorbidity context
                activity = _activity_descriptor(flag, mean_dd)
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation. {note}. "
                    f"Elevated frontal-central beta is most consistently observed in "
                    f"MDD comorbid with anxiety symptoms; this finding should be "
                    f"contextualised with the subject's anxiety symptom history."
                )
            elif name == "Alpha_Power":
                # Alpha_Power STRONG (reduced): use correct mechanism framing
                activity = _activity_descriptor(flag, mean_dd)
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation, indicating impaired cortical inhibitory "
                    f"efficiency and disrupted fronto-parieto-occipital connectivity. "
                    f"{note}."
                )
            else:
                activity = _activity_descriptor(flag, mean_dd)
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation. {note}."
                )

        elif flag == ClinicalFlag.MODERATE:
            activity = _activity_descriptor(flag, mean_dd)
            if name == "Coherence":
                biomarker_lines.append(
                    f"{desc}: Interhemispheric alpha coherence showed a moderate "
                    f"elevation relative to normative expectation, suggesting a partial "
                    f"loss of functional connectivity selectivity rather than a dominant "
                    f"network-level abnormality. Elevated coherence is the MDD-associated "
                    f"pattern described by Leuchter et al. (2012), but the effect size "
                    f"here was secondary rather than primary."
                )
            elif name == "TBR":
                biomarker_lines.append(
                    f"{desc}: In this recording, the theta/beta ratio was {activity} "
                    f"relative to normative expectation, indicating a moderate reduction "
                    f"in frontal arousal efficiency. {note}. This finding should be "
                    f"interpreted cautiously because TBR is a general cortical arousal "
                    f"construct and has not been established as a specific MDD biomarker."
                )
            elif name == "FAA":
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation, indicating a moderate hemispheric imbalance "
                    f"in frontal alpha organisation. {note}. FAA carries limited "
                    f"standalone diagnostic specificity and should be weighted as a "
                    f"secondary biomarker signal."
                )
            elif name == "Beta_Power":
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation, indicating a moderate degree of frontal-central "
                    f"cortical hyperactivation. {note}. Elevated beta is most commonly "
                    f"contextualised alongside anxiety symptoms rather than interpreted as "
                    f"a depression-specific abnormality."
                )
            elif name == "Alpha_Power":
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation, indicating a moderate reduction in posterior "
                    f"cortical inhibitory efficiency. {note}."
                )
            else:
                biomarker_lines.append(
                    f"{desc}: In this recording, activity was {activity} relative to "
                    f"normative expectation. The magnitude of deviation was moderate and "
                    f"did not represent the dominant biomarker abnormality in this profile. "
                    f"{note}."
                )

        elif flag == ClinicalFlag.SUPPRESSOR:
            if name == "Coherence":
                # CRITICAL CORRECTION: Coherence SUPPRESSOR = normative coherence =
                # preserved connectivity selectivity = HEALTHY finding.
                # Do NOT describe as "reduced coherence indicating impaired communication."
                biomarker_lines.append(f"{desc}: {_coherence_suppressor_note()}")
            elif name == "FAA":
                # FAA SUPPRESSOR: healthy asymmetry + evidence caveat
                context = _suppressor_context(raw_label)
                biomarker_lines.append(
                    f"{desc}: Frontal alpha asymmetry was within the expected normative "
                    f"range in this recording, indicating no clinically significant "
                    f"hemispheric motivational lateralisation imbalance. "
                    f"Bilateral motivational balance was {context}. "
                    f"FAA carries limited standalone diagnostic weight given its "
                    f"heterogeneous meta-analytic evidence base in MDD."
                )
            elif name == "TBR":
                context = _suppressor_context(raw_label)
                biomarker_lines.append(
                    f"{desc}: The theta/beta ratio was within the expected normative "
                    f"range in this recording, indicating no significant frontal arousal "
                    f"imbalance. Frontal arousal efficiency was {context}. "
                    f"TBR is a general arousal construct not specific to MDD; "
                    f"its normative status here is consistent with the overall profile."
                )
            elif name == "Alpha_Power":
                context = _suppressor_context(raw_label)
                biomarker_lines.append(
                    f"{desc}: Parieto-occipital alpha power was within the expected "
                    f"normative range in this recording, indicating intact cortical "
                    f"inhibitory efficiency and preserved fronto-parieto-occipital "
                    f"connectivity. Posterior alpha was {context}, with no disruption "
                    f"to sensory gating or resting-state cortical regulation identified."
                )
            elif name == "Beta_Power":
                context = _suppressor_context(raw_label)
                biomarker_lines.append(
                    f"{desc}: Frontal-central beta power was within the expected "
                    f"normative range in this recording, indicating no cortical "
                    f"hyperactivation or prefrontal dysregulation. Beta power was "
                    f"{context}; no deviation consistent with anxious cortical "
                    f"overactivation was identified."
                )
            else:
                context = _suppressor_context(raw_label)
                biomarker_lines.append(
                    f"{desc}: Values for this measure were within the expected normative "
                    f"range in this recording. "
                    f"{note.rstrip('.').capitalize() if note else desc} was {context}, "
                    f"indicating no clinically significant deviation in this domain."
                )

        else:
            # WEAK
            weak_effect_note = _weak_effect_note(tcav)
            if name == "FAA":
                biomarker_lines.append(
                    f"{desc}: Frontal alpha asymmetry was within the expected normative "
                    f"range in this recording. No significant hemispheric imbalance in "
                    f"frontal inhibitory activity was identified. FAA carries limited "
                    f"standalone diagnostic weight given its heterogeneous meta-analytic "
                    f"evidence base as an MDD discriminator. {weak_effect_note}".strip()
                )
            elif name == "TBR":
                biomarker_lines.append(
                    f"{desc}: The theta/beta ratio was within expected limits in this "
                    f"recording, indicating no significant frontal arousal imbalance. "
                    f"TBR is a general cortical arousal construct not specific to MDD "
                    f"and does not represent a clinically significant deviation here. "
                    f"{weak_effect_note}".strip()
                )
            elif name == "Coherence":
                biomarker_lines.append(
                    f"{desc}: Interhemispheric alpha coherence was within the expected "
                    f"normative range in this recording, indicating preserved functional "
                    f"connectivity selectivity. The MDD-associated pattern is elevated "
                    f"coherence (Leuchter et al. 2012); normative values confirm intact "
                    f"bilateral cortical coordination in this subject. "
                    f"{weak_effect_note}".strip()
                )
            else:
                biomarker_lines.append(
                    f"{desc}: Values for this measure were within the expected normative "
                    f"range in this recording. This indicates that "
                    f"{note.rstrip('.').lower() if note else desc.lower()} "
                    f"does not represent a clinically significant deviation in this subject. "
                    f"{weak_effect_note}".strip()
                )

    concept_summary = (
        "\n\n".join(biomarker_lines)
        if biomarker_lines
        else "No biomarker findings were available for this recording."
    )

    # --- Cross-biomarker reasoning notes ---
    theta = next((c for c in concepts if c["name"] == "Theta"), None)
    faa = next((c for c in concepts if c["name"] == "FAA"), None)
    coh = next((c for c in concepts if c["name"] == "Coherence"), None)

    pattern_note = ""
    if theta and theta["clinical_flag"] in {ClinicalFlag.STRONG, ClinicalFlag.MODERATE}:
        if not faa or faa["clinical_flag"] not in {ClinicalFlag.STRONG, ClinicalFlag.MODERATE}:
            pattern_note += (
                " The absence of concurrent frontal asymmetry suggests a non-lateralised "
                "prefrontal regulatory disturbance rather than a hemispheric imbalance pattern."
            )
    # CORRECTION: Coherence SUPPRESSOR means normative coherence = healthy.
    # Do NOT add a note about "reduced coherence indicating impaired communication."
    if coh and coh["clinical_flag"] in {ClinicalFlag.STRONG, ClinicalFlag.MODERATE}:
        # Elevated coherence = loss of connectivity selectivity = notable finding
        pattern_note += (
            " Elevated interhemispheric alpha coherence reflects a loss of functional "
            "connectivity selectivity, a pattern associated with MDD (Leuchter et al. 2012)."
        )

    # --- Clinical Interpretation ---
    if active_abnormal:
        active_names = [c["description"] or c["name"] for c in active_abnormal]
        if len(active_names) == 1:
            dominant_text = (
                f"The neurophysiological profile of this subject is characterised by a focal "
                f"{dominant_family} abnormality, with {active_names[0]} representing the primary "
                f"deviation from normative expectation."
            )
        else:
            listed = ", ".join(active_names[:-1]) + f" and {active_names[-1]}"
            dominant_text = (
                f"The neurophysiological profile of this subject is characterised by "
                f"{dominant_family} dysregulation, with {listed} each showing a clinically "
                f"meaningful deviation from normative expectation."
            )
    elif raw_label == "MDD" and suppressors:
        sup_names = [c["description"] or c["name"] for c in suppressors]
        listed = (
            sup_names[0] if len(sup_names) == 1
            else ", ".join(sup_names[:-1]) + f" and {sup_names[-1]}"
        )
        dominant_text = (
            f"The neurophysiological profile of this subject shows preserved "
            f"{dominant_family} measures across the assessed biomarker domains, "
            f"with {listed} each within normative limits."
        )
    else:
        dominant_text = (
            "The neurophysiological profile of this subject is broadly within expected "
            "limits across all assessed biomarker domains. No clinically significant "
            "deviation from normative expectation was identified in this recording."
        )

    # Dissociation note
    dissociation_text = ""
    intact_concepts = suppressors + weak
    if active_abnormal and intact_concepts:
        intact_names = [c["description"] or c["name"] for c in intact_concepts]
        intact_listed = (
            intact_names[0] if len(intact_names) == 1
            else ", ".join(intact_names[:-1]) + f" and {intact_names[-1]}"
        )
        dissociation_text = (
            f" In contrast, {intact_listed} "
            f"{'was' if len(intact_names) == 1 else 'were'} within the expected normative "
            f"range, indicating that the neurophysiological disturbance in this subject is "
            f"domain-selective rather than diffuse. This dissociation may reflect a focal "
            f"or early-stage process, or heterogeneity in the underlying presentation."
        )

    # Evidence-weight note for FAA
    faa_obj = next((c for c in concepts if c["name"] == "FAA"), None)
    faa_note = ""
    if faa_obj:
        faa_note = (
            " Frontal alpha asymmetry (FAA) was within expected limits in this recording. "
            "Given FAA's heterogeneous meta-analytic evidence base as an MDD discriminator, "
            "this measure carries limited interpretive weight in the overall profile assessment."
        )

    # Evidence-weight note for TBR
    tbr_obj = next((c for c in concepts if c["name"] == "TBR"), None)
    tbr_note = ""
    if tbr_obj and tbr_obj["clinical_flag"] in {ClinicalFlag.STRONG, ClinicalFlag.MODERATE}:
        tbr_note = (
            " The theta/beta ratio, while elevated, is a general arousal construct "
            "derived from the ADHD literature and has not been established as a specific "
            "MDD biomarker; it carries lower interpretive weight than spectral power "
            "and coherence measures in this context."
        )

    clinical_interpretation = (
        f"{dominant_text}{dissociation_text}{faa_note}{tbr_note}{pattern_note}\n\n"
        "EEG findings reflect the subject's neurophysiological state at the time of "
        "recording. These observations require integration with clinical history, current "
        "symptom presentation, and professional clinical evaluation. They do not constitute "
        "a standalone diagnosis."
    )

    # --- Confidence & Reliability Assessment ---
    mean_cav = (
        sum(c["cav_accuracy"] for c in concepts) / len(concepts) if concepts else 0.0
    )

    strong_count = len(strong)
    moderate_count = len(moderate)
    suppressor_count = len(suppressors)
    active_count = strong_count + moderate_count + suppressor_count

    if strong_count >= 2 and suppressor_count == 0:
        overall_reliability = "High"
        clinical_reliance = (
            "Findings are suitable as a primary decision-support signal, "
            "subject to clinical correlation."
        )
    elif strong_count == 1 and moderate_count >= 1 and confidence_pct >= 90 and mean_cav >= 80:
        overall_reliability = "High"
        clinical_reliance = (
            "Findings are suitable as a primary decision-support signal, "
            "subject to clinical correlation."
        )
    elif active_count == 0:
        overall_reliability = "Low"
        clinical_reliance = (
            "Findings are indicative only; clinical assessment should take "
            "precedence over this report."
        )
    elif confidence_pct >= 90 and "stable" in consistency and mean_cav >= 80:
        overall_reliability = "High"
        clinical_reliance = (
            "Findings are suitable as a primary decision-support signal, "
            "subject to clinical correlation."
        )
    elif confidence_pct >= 70 and mean_cav >= 65:
        overall_reliability = "Moderate"
        clinical_reliance = (
            "Findings are suitable as supplementary decision-support information. "
            "Clinical interview and symptom assessment are recommended before clinical action."
        )
    else:
        overall_reliability = "Low"
        clinical_reliance = (
            "Findings are indicative only; clinical assessment should take "
            "precedence over this report."
        )

    # Differential evidence-weight note for FAA and TBR in reliability section
    low_weight_names = [
        c["name"] for c in concepts if c["name"] in {"FAA", "TBR"}
    ]
    if low_weight_names:
        low_weight_str = " and ".join(low_weight_names)
        evidence_caveat = (
            f" {low_weight_str} carry lower interpretive weight  "
            f"{'FAA has a heterogeneous meta-analytic evidence base as an MDD discriminator' if 'FAA' in low_weight_names else ''}"
            f"{'; ' if 'FAA' in low_weight_names and 'TBR' in low_weight_names else ''}"
            f"{'TBR is a general arousal construct not specific to MDD' if 'TBR' in low_weight_names else ''}."
        )
    else:
        evidence_caveat = ""

    concept_reliability_text = (
        "Biomarker concept separation was well-established across assessed domains."
        if mean_cav >= 80
        else "Biomarker concept boundaries showed moderate reliability in this recording."
        if mean_cav >= 65
        else "Biomarker concept separation was limited in this recording, reducing "
             "confidence in individual biomarker findings."
    ) + evidence_caveat

    reliability = (
        f"Prediction confidence was {confidence_pct:.1f}% ({band.lower()}). "
        f"{'The classification remained stable across recording segments, supporting the reliability of this output.' if 'stable' in consistency else 'Classification confidence showed marked variability across segments, which limits overall reliability.'}\n\n"
        f"{concept_reliability_text} Overall biomarker evidence is assessed as "
        f"{overall_reliability.lower()} reliability.\n\n"
        f"{clinical_reliance}"
    )
    if technical_note:
        reliability += f"\n\nTechnical note: {technical_note}"

    return {
        "patient_recording_information": patient_info,
        "model_prediction_summary": model_summary,
        "concept_based_explanation": concept_summary,
        "clinical_interpretation": clinical_interpretation,
        "confidence_reliability_assessment": reliability,
        "safety_disclaimer": SAFETY_DISCLAIMER,
        "raw_report_text": "",
        "source": "local",
    }


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_report(analysis_result: dict) -> dict:
    payload = {
        "contents": [{"parts": [{"text": _build_prompt(analysis_result)}]}],
        "generationConfig": {
            "temperature": 0.15,
            "maxOutputTokens": 3072,
            "topP": 0.8,
        },
    }

    last_error: str | None = None
    for attempt in range(3):
        try:
            resp = requests.post(
                GEMINI_MODEL_URL,
                headers={
                    "x-goog-api-key": GEMINI_API_KEY,
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=60,
            )
        except requests.exceptions.RequestException as exc:
            last_error = f"Network error: {exc}"
            if attempt < 2:
                time.sleep(1.5 * (attempt + 1))
            continue

        if resp.status_code == 200:
            raw_text = resp.json()["candidates"][0]["content"]["parts"][0]["text"]
            parsed = _parse_sections(raw_text)
            for key in parsed:
                parsed[key] = _clean_report_text(parsed[key])
            parsed["raw_report_text"] = _clean_report_text(raw_text)
            parsed["source"] = "gemini"
            return parsed

        last_error = f"Gemini API error {resp.status_code}: {resp.text}"
        if resp.status_code not in {429, 500, 503} or attempt == 2:
            break
        time.sleep(1.5 * (attempt + 1))

    return _build_local_report(analysis_result, technical_note=last_error)
